/* Main.c file generated by New Project wizard
 *
 * Created:   seg out 3 2022
 * Processor: 80C51
 * Compiler:  SDCC for 8051
 */

#include <at89x52.h>

//Declarações de Variáveis
int vagas = 20;
unsigned char tabela[21]= {0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x10,0x11,0x12,0x13,0x14,0x15,0x16,0x17,0x18,0x19,0x20};
int reg1;
int reg2;


//int 0 = entrada (decrementa vaga)
void int_ext1() __interrupt (2)
{
	vagas--;
}

//int1 = saída (incrementa vaga)
void int_ext0() __interrupt (0)
{
	vagas++;
}

void main(void)
 {  
   // Write your code here
     //Configurar os registradores
     EA = 1; // habilito  interrupçao
     EX1 = 1; // habilita externa 1
	 EX0 = 1;
     IT1 = 1; // configura como borda de descida
	 IT0 = 1;
     P1_5 = 0; // valor inicial para porta p1_
	while (1)
		{
			
			//reg1=vagas/10; //Dezenas
			//reg2=vagas%10; //Unidades
			//reg1=reg1<<4;
			P2 = tabela[vagas];		
			if (vagas==0){
				P2 = 00;
			};
} 
}